AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-rust-hello-word
      CodeUri: build/distributions/aws-lambda-rust-hello-word-1.0.zip
      Handler: bootstrap
      Runtime: provided.al2
      Description: Rust function
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active