
POST https://ugju3p38s1.execute-api.us-east-1.amazonaws.com/dev/aws-lambda-rust-hello-word HTTP/1.1
content-type: application/json

{
    "username": "demiusacademius",
    "password": "Keiko&Matsui2"
}

####

GET https://ugju3p38s1.execute-api.us-east-1.amazonaws.com/dev/aws-lambda-rust-hello-word?username=demiusacademius HTTP/1.1
